# Generated by Django 6.0.1 on 2026-04-18 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeChecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField()),
                ('skills', models.JSONField()),
                ('total_experience', models.CharField(max_length=100)),
                ('project_categories', models.JSONField()),
                ('resume_summary', models.TextField(blank=True)),
                ('raw_data', models.JSONField()),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeChecker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeChecker.resume')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
