# Generated by Django 6.0.1 on 2026-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeChecker', '0002_jobdescription_created_at_resume_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
